//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int UserId { get; set; }
        public int IdSanPham { get; set; }
        public string TenSanPham { get; set; }
        public decimal Gia { get; set; }
        public int SoLuong { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual User User { get; set; }
    }
}
