//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedLoginHistory
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public System.DateTime AttemptTime { get; set; }
        public string IPAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
